name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write # Needed for GitHub publishing
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        uses: quintenroets/actions/validate/npm@main

      - name: Publish npm project to GitHub
        uses: quintenroets/actions/publish/npm@main
